version: "3.8"

services:
  postgres:
      image: postgres:15
      container_name: capstone_postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: capstone_user
        POSTGRES_PASSWORD: accenturer25
        POSTGRES_DB: capstone_db
      ports:
        - "5434:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U capstone_user"]
        interval: 10s
        timeout: 5s
        retries: 5
  
volumes:
  pgdata: